# Generated by Django 4.1.6 on 2023-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_details',
            fields=[
                ('Train_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Train_name', models.CharField(max_length=260, unique=True)),
                ('Origin_city', models.CharField(max_length=260)),
                ('Destination_city', models.CharField(max_length=260)),
                ('Departure_time', models.TimeField()),
                ('Arrival_time', models.TimeField()),
            ],
        ),
    ]
