# Generated by Django 4.1.6 on 2023-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.PositiveIntegerField()),
                ('origin_city', models.CharField(max_length=260)),
                ('destination_city', models.CharField(max_length=260)),
                ('train_fare', models.PositiveIntegerField()),
            ],
        ),
    ]
